site_name: Aweit Docs
site_url: https://aweit-zhu.github.io
site_author: weizhi.zhu
site_description: a short description of your website

nav:
  - Algorithm - LRU 快取: lru.md
  - Algorithm - Dynamic Programming : dp.md
  - Java Regular Expression: regex.md
  - JVM - Stack & Heap: stackheap.md
  - Binary & Bit Shift: binaryOperator.md
  - ForkJoinPool: forkJoinPool.md
  - Volatile & synchronized: volatile.md
  - Thread & Semaphore: semaphore.md
  - Java 8 CompletableFuture: completableFuture.md
  - Java Thread & Thread Pool : thread.md
  - Spring Boot 3 + Spring Batch 5: spring-batch.md
  - Struts2 + struts-tags: struts-tags.md
  - Struts2 + ValueStack + Form Validate: struts-valuestack.md
  - Struts2 Properties Config: struts-props.md
  - Struts2 + Apache Tiles: tiles.md
  - SSH (Struts2 + Spring5 + Hibernate4): ssh.md
  - Spring Cloud - OpenFeign Client: spring-cloud-feign.md
  - Spring Cloud - Config Server: spring-cloud-config.md
  - Spring Cloud - Eureka Server: spring-cloud-eureka.md
  - Spring Security & LDAP: spring-ldap.md
  - Spring Boot 3 and Keycloak: spring-keycloak.md
  - Spring Data JPA: spring-data-jpa.md
  - Spring Boot 3 and Spring Security 6 (JWT Authentication and Authorization): spring-security.md
  - FlutterFire: flutter.md
  - NFS: nfs.md
  - Velero: velero.md
  - Treafik: traefik.md
  - Dapr: dapr.md
  - Docker: docker.md
  - Kubernetes: practicek8s.md
  - SonarQube: sonarqube.md
  - Drone: drone.md
  - Microk8s: microk8s.md
  - About: index.md
theme:
  features:
    - content.code.copy
  name: material
  highlightjs: true
  hljs_languages:
    - yaml